version: "3.9"

services:
  postgres:
    image: postgres:18
    restart: unless-stopped
    environment:
      POSTGRES_USER: testpsql
      POSTGRES_PASSWORD: testpsql
      POSTGRES_DB: gentypes
    ports:
      - "15432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data:
